name: OCI ARM Fisher
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  launch-instance:
    runs-on: ubuntu-latest
    steps:
      - name: Install OCI CLI
        run: |
          pip install oci-cli
          mkdir -p ~/.oci

      - name: Try to Launch ARM Instance (High Frequency)
        run: |
          for i in 1 2 3; do
            echo "--- Tentativa $i de 3 ---"
            oci compute instance launch \
              --compartment-id "${{ secrets.OCI_TENANCY_OCID }}" \
              --availability-domain "IQFJ:SA-VINHEDO-1-AD-1" \
              --shape "VM.Standard.A1.Flex" \
              --image-id "${{ secrets.OCI_IMAGE_ID }}" \
              --subnet-id "${{ secrets.OCI_SUBNET_ID }}" \
              --shape-config '{"ocpus": 4, "memoryInGBs": 24}' \
              --assign-public-ip true \
              --display-name "Ollama-Server-Prod" \
              --ssh-authorized-keys-file <(echo "${{ secrets.SSH_PUBLIC_KEY }}") && { echo "!!! SUCESSO !!! VM CRIADA."; exit 0; }
            
            echo "Sem capacidade. Esperando 20s para a próxima tentativa..."
            sleep 20
          done
          echo "Fim do ciclo de 5 minutos. O GitHub Actions tentará novamente em breve."
